[package]
name = "quench-auth"
version = "0.3.4"
edition = { workspace = true }
authors = { workspace = true }
description = "Quench - authentication and JWT handling"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = "README.md"

[lib]
name = "quench_auth"
path = "src/lib.rs"

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
argon2 = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
ed25519-dalek = { version = "2", features = ["pkcs8", "rand_core"] }
envmnt = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
jsonwebtoken = { workspace = true }
quench-cache = { workspace = true, features = ["redis"] }
quench-db = { workspace = true }
rand = "0.8"
rand_core = { version = "0.6", features = ["getrandom"] }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true }
