[package]
name = "quench-http"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
description = "Quench - lightweight HTTP framework with annotation-driven discovery and dependency injection"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[lib]
name = "quench_http"
path = "src/lib.rs"

[dependencies]
actix-router = { workspace = true }
async-trait = { workspace = true }
bytes = { version = "1.12" }
bytestring = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["server", "http1", "http2"] }
hyper-util = { workspace = true, features = ["tokio", "server-auto", "server-graceful"] }
inventory = { workspace = true }
multer = { workspace = true }
quench-http-macros = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
