[package]
name = "quench-http-macros"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
description = "Quench - proc macros for quench-http (route + injectable discovery)"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
