[package]
name = "quench-starter"
version = "0.1.5"
edition = { workspace = true }
authors = { workspace = true }
description = "Quench - server bootstrap and utilities"
keywords = ["development", "tools"]
categories = ["development-tools"]
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }

[lib]
name = "quench_starter"
path = "src/lib.rs"

[dependencies]
actix-service = { workspace = true }
actix-web = { workspace = true }
dotenvy = { workspace = true }
futures-util = { workspace = true }
envmnt = { workspace = true }
quench-cli = { workspace = true }
quench-auth = { workspace = true }
quench-db = { workspace = true }
quench-web = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
